export const ListMessageExample = [
  'Bacon ipsum dolor amet turkey short ribs venison, doner kielbasa tri-tip shoulder flank picanha tail beef ribs.',
  'Bacon ipsum dolor amet buffalo shankle turkey shoulder flank.',
  'Bacon ipsum dolor amet bresaola salami t-bone drumstick fatback capicola.',
  'Bacon ipsum dolor amet prosciutto drumstick jowl hamburger, ground round capicola burgdoggen biltong fatback short ribs pig beef ribs pork loin short loin porchetta beef brisket buffalo, drumstick jowl frankfurter sirloin tongue nisi ut aliquip ex ea commodo consequat.',
  'Bacon ipsum dolor amet shank kevin tongue, doner jerky leberkas flank biltong ribeye ground round cow.',
  'Bacon ipsum dolor amet pancetta bacon t-bone kevin short loin porchetta beef brisket buffalo fatback pork turducken pig.',
  'Bacon ipsum dolor amet frankfurter doner turducken, shoulder leberkas jerky filet mignon beef ribs tongue pancetta corned beef sirloin tail.',
  'Bacon ipsum dolor amet short loin turducken bresaola t-bone capicola doner.',
  'Bacon ipsum dolor amet jerky salami ball tip pork loin.',
  'Bacon ipsum dolor amet ham turkey hamburger beef ribs shank t-bone.',
  'Bacon ipsum dolor amet leberkas drumstick andouille meatball bresaola jowl bacon boudin tongue ribeye shankle.',
  'Bacon ipsum dolor amet rump ham short loin pork kevin ground round andouille strip steak beef ribs frankfurter doner.',
  'Bacon ipsum dolor amet short ribs filet mignon pastrami, landjaeger pork loin leberkas meatball ball tip corned beef t-bone pancetta.',
  'Bacon ipsum dolor amet pig jowl hamburger picanha cupim landjaeger venison.',
  'Bacon ipsum dolor amet porchetta tri-tip cupim picanha, sausage leberkas pastrami ham hock.',
  'Bacon ipsum dolor amet landjaeger cupim tail burgdoggen hamburger tri-tip.',
  'Bacon ipsum dolor amet salami corned beef shankle, shank alcatra beef ribs spare ribs buffalo tri-tip ham pancetta t-bone nisi ut aliquip ex ea commodo consequat andouille burgdoggen landjaeger pork loin leberkas meatball ball, drumstick jowl frankfurter sirloin tongue.',
  'Bacon ipsum dolor amet picanha frankfurter rump buffalo strip steak doner spare ribs brisket drumstick ribeye bresaola kevin shankle tri-tip pig.',
  'Bacon ipsum dolor amet tongue meatball filet mignon salami tri-tip.',
  'Bacon ipsum dolor amet t-bone kevin andouille salami beef pastrami brisket tri-tip buffalo biltong.',
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
];